name: sameep
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.2.1
  - r-tidyverse=1.3.2
  - r-ggtext=0.1.2
  - r-tidymodels=1.0.0
  - r-doparallel=1.0.17
  - r-ranger=0.14.1
  - r-metrics=0.1.4
  - r-showtext=0.9_5
  - r-sf=1.0_7
  - r-rgdal=1.5_32
  - r-raster=3.5_21
  - r-sen2r=1.5.3
  - r-randomforest=4.7_1.1
  - r-plotly=4.10.1
  - snakemake=7.18.2
  - graphviz=6.0.1
